remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-feed
- jekyll-coffeescript

title: AIOTI Ontology Landscape
description: Catalogue of Ontologies for Semantic Interoperability

github:
  is_project_page: false

collections:
  solutions:
    output: true

sass:
  style: compact